services:
  mongo_db:
    image: mongo:latest
    container_name: persistent_store
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:27017"
    healthcheck:
      test: [
        "CMD",
        "mongosh",
        "--username",
        "${DB_USERNAME}",
        "--password",
        "${DB_PASSWORD}",
        "--authenticationDatabase",
        "admin",
        "--eval",
        "db.adminCommand('ping').ok",
        "--quiet"
      ]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: cache
    command: [
      "redis-server",
      "--aclfile",
      "/usr/local/etc/redis/users.acl",
      "--appendonly",
      "yes"
    ]
    ports:
      - "${CACHE_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${CACHE_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - redis_data:/data
      - ./users.acl:/usr/local/etc/redis/users.acl:ro
    networks:
      - app-network

  spring-app:
    build: .
    container_name: url_shortener
    ports:
      - "${APP_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_MONGODB_URI: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo_db:27017/${DB_NAME}?authSource=admin
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_USERNAME: default
      SPRING_DATA_REDIS_PASSWORD: ${CACHE_PASSWORD}
      SPRING_DATA_REDIS_DATABASE: 0
    depends_on:
      mongo_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge
