spring.application.name=url-shortener
server.forward-headers-strategy=framework
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb=DEBUG
