spring.application.name=url-shortener
spring.config.import=file:.env[.properties]
spring.data.mongodb.uri=mongodb://${DB_USERNAME}:${DB_PASSWORD}@localhost:27017/${DB_NAME}?authSource=admin
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.username=default
spring.data.redis.password=${CACHE_PASSWORD}
spring.data.redis.database=0
spring.data.redis.timeout=5000ms
# Tells Spring to look at X-Forwarded-Host headers sent by your proxy/load balancer
server.forward-headers-strategy=framework
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
logging.level.com.training.url_shortener=DEBUG
